# Generated by Django 3.1.7 on 2021-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/images'),
        ),
    ]
